name: Build Windows App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    env:
      CMAKE_GENERATOR: Visual Studio 17 2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: stable

      - name: Remove old Windows files
        shell: pwsh
        run: |
          if (Test-Path windows) {
            Remove-Item windows -Recurse -Force
          }
          if (Test-Path build) {
            Remove-Item build -Recurse -Force
          }

      - name: Create Windows project
        run: flutter create --platforms=windows --org com.digital24online .

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive `
            -Path build\windows\x64\runner\Release\* `
            -DestinationPath Digital24Online-Billing-Windows.zip

      - name: Upload Windows App
        uses: actions/upload-artifact@v4
        with:
          name: Digital24Online-Billing-Windows
          path: Digital24Online-Billing-Windows.zip
